# -*- coding: utf-8 -*-c

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 357)
        Dialog.setStyleSheet("background-color: #f2f2f2;\n"
"border-radius: 10px;\n"
"")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 40, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditUser = QtWidgets.QLineEdit(Dialog)
        self.lineEditUser.setGeometry(QtCore.QRect(40, 100, 311, 31))
        self.lineEditUser.setStyleSheet("QLineEdit {\n"
"    padding: 6px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.lineEditUser.setObjectName("lineEditUser")
        self.lineEditPass = QtWidgets.QLineEdit(Dialog)
        self.lineEditPass.setGeometry(QtCore.QRect(40, 180, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditPass.setFont(font)
        self.lineEditPass.setAutoFillBackground(False)
        self.lineEditPass.setStyleSheet("QLineEdit {\n"
"    padding: 6px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.lineEditPass.setObjectName("lineEditPass")
        self.btnLogin = QtWidgets.QPushButton(Dialog)
        self.btnLogin.setGeometry(QtCore.QRect(40, 230, 311, 31))
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogin.setStyleSheet("QPushButton {\n"
"    background-color: #1c1c1c;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #333333;\n"
"}\n"
"")
        self.btnLogin.setObjectName("btnLogin")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(100, 280, 231, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_4.setObjectName("label_4")
        self.labelAviso = QtWidgets.QLabel(Dialog)
        self.labelAviso.setGeometry(QtCore.QRect(70, 300, 251, 16))
        self.labelAviso.setStyleSheet("color: red;\n"
"")
        self.labelAviso.setText("")
        self.labelAviso.setObjectName("labelAviso")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Bem vindo ao Pegasus 1.1 ®"))
        self.label_2.setText(_translate("Dialog", "Usuário"))
        self.label_3.setText(_translate("Dialog", "Senha"))
        self.lineEditUser.setPlaceholderText(_translate("Dialog", "Insira seu login"))
        self.lineEditPass.setPlaceholderText(_translate("Dialog", "Insira sua senha"))
        self.btnLogin.setText(_translate("Dialog", "Entrar "))
        self.label_4.setText(_translate("Dialog", "Esqueceu sua senha? Clique aqui."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
