# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet(" background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.btn10 = QtWidgets.QPushButton(self.widget_2)
        self.btn10.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn10.setFont(font)
        self.btn10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn10.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/cotonete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn10.setIcon(icon)
        self.btn10.setIconSize(QtCore.QSize(48, 48))
        self.btn10.setObjectName("btn10")
        self.gridLayout.addWidget(self.btn10, 4, 2, 1, 1)
        self.btn15 = QtWidgets.QPushButton(self.widget_2)
        self.btn15.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn15.setFont(font)
        self.btn15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn15.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/maquina-de-lavar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn15.setIcon(icon1)
        self.btn15.setIconSize(QtCore.QSize(48, 48))
        self.btn15.setObjectName("btn15")
        self.gridLayout.addWidget(self.btn15, 6, 0, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.widget_2)
        self.btn2.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/diamond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn2.setIcon(icon2)
        self.btn2.setIconSize(QtCore.QSize(48, 48))
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 4, 4, 1, 1)
        self.btn16 = QtWidgets.QPushButton(self.widget_2)
        self.btn16.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn16.setFont(font)
        self.btn16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn16.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/log-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn16.setIcon(icon3)
        self.btn16.setIconSize(QtCore.QSize(48, 48))
        self.btn16.setObjectName("btn16")
        self.gridLayout.addWidget(self.btn16, 6, 4, 1, 2)
        self.btn9 = QtWidgets.QPushButton(self.widget_2)
        self.btn9.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn9.setFont(font)
        self.btn9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn9.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/sabao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn9.setIcon(icon4)
        self.btn9.setIconSize(QtCore.QSize(48, 48))
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 4, 1, 1, 1)
        self.btn12 = QtWidgets.QPushButton(self.widget_2)
        self.btn12.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn12.setFont(font)
        self.btn12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn12.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/lavando-roupas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn12.setIcon(icon5)
        self.btn12.setIconSize(QtCore.QSize(48, 48))
        self.btn12.setObjectName("btn12")
        self.gridLayout.addWidget(self.btn12, 3, 3, 1, 1)
        self.btn14 = QtWidgets.QPushButton(self.widget_2)
        self.btn14.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn14.setFont(font)
        self.btn14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn14.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn14.setIcon(icon6)
        self.btn14.setIconSize(QtCore.QSize(48, 48))
        self.btn14.setObjectName("btn14")
        self.gridLayout.addWidget(self.btn14, 4, 3, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.widget_2)
        self.btn5.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn5.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/paycheck.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn5.setIcon(icon7)
        self.btn5.setIconSize(QtCore.QSize(48, 48))
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 3, 0, 1, 3)
        self.btn11 = QtWidgets.QPushButton(self.widget_2)
        self.btn11.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn11.setFont(font)
        self.btn11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn11.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/ferro-de-passar-roupas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn11.setIcon(icon8)
        self.btn11.setIconSize(QtCore.QSize(48, 48))
        self.btn11.setObjectName("btn11")
        self.gridLayout.addWidget(self.btn11, 4, 5, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.widget_2)
        self.btn1.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn1.setToolTip("")
        self.btn1.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/cutting-with-a-scissor-on-broken-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn1.setIcon(icon9)
        self.btn1.setIconSize(QtCore.QSize(50, 50))
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 0, 4, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.widget_2)
        self.btn6.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn6.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/jeans.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn6.setIcon(icon10)
        self.btn6.setIconSize(QtCore.QSize(48, 48))
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 0, 5, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.widget_2)
        self.btn8.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn8.setFont(font)
        self.btn8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn8.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/shorts (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn8.setIcon(icon11)
        self.btn8.setIconSize(QtCore.QSize(48, 48))
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 3, 4, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.widget_2)
        self.btn4.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn4.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/encrypted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn4.setIcon(icon12)
        self.btn4.setIconSize(QtCore.QSize(48, 48))
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 3, 5, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.widget_2)
        self.btn3.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/financial-report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn3.setIcon(icon13)
        self.btn3.setIconSize(QtCore.QSize(48, 48))
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 0, 0, 1, 3)
        self.btn7 = QtWidgets.QPushButton(self.widget_2)
        self.btn7.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn7.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/to-do-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn7.setIcon(icon14)
        self.btn7.setIconSize(QtCore.QSize(48, 48))
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 0, 3, 1, 1)
        self.btn13 = QtWidgets.QPushButton(self.widget_2)
        self.btn13.setMinimumSize(QtCore.QSize(140, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn13.setFont(font)
        self.btn13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn13.setStyleSheet("QPushButton {\n"
"    background-color: rgba(245, 250, 255, 0.6);  /* Branco off-white azulado translúcido */\n"
"    color: #1c1c1c;\n"
"    border: 2px solid #2e3b4e;                  /* Borda escura azulada */\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    backdrop-filter: blur(3px);                 /* (funciona em algumas integrações) */\n"
"    box-shadow: inset 0 0 10px rgba(200, 220, 255, 0.3);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.8);  /* Clareia ao passar o mouse */\n"
"    border: 2px solid #1f2a3c;\n"
"    box-shadow: 0 0 12px rgba(180, 200, 255, 0.6), inset 0 0 6px rgba(180, 200, 255, 0.4);\n"
"    transform: scale(1.02);                     /* Leve zoom */\n"
"}\n"
"")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/dinheiro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn13.setIcon(icon15)
        self.btn13.setIconSize(QtCore.QSize(48, 48))
        self.btn13.setObjectName("btn13")
        self.gridLayout.addWidget(self.btn13, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">PORTAL JEANS BENEFICIAMENTO</span></p></body></html>"))
        self.btn10.setText(_translate("MainWindow", "Contonete"))
        self.btn15.setText(_translate("MainWindow", "Lixado"))
        self.btn2.setText(_translate("MainWindow", "Diferenciado"))
        self.btn16.setText(_translate("MainWindow", "Sair"))
        self.btn9.setText(_translate("MainWindow", "Natoon"))
        self.btn12.setText(_translate("MainWindow", "Used"))
        self.btn14.setText(_translate("MainWindow", "Horas Extras"))
        self.btn5.setText(_translate("MainWindow", "Folha de\n"
"Pagamento"))
        self.btn11.setText(_translate("MainWindow", "Passadoria"))
        self.btn1.setText(_translate("MainWindow", "Entrada de \n"
"corte"))
        self.btn6.setText(_translate("MainWindow", "Amassado"))
        self.btn8.setText(_translate("MainWindow", "Saída de \n"
"Romaneios"))
        self.btn4.setText(_translate("MainWindow", "Reservado"))
        self.btn3.setText(_translate("MainWindow", "DARFS"))
        self.btn7.setText(_translate("MainWindow", "Acertos de \n"
"Romaneios"))
        self.btn13.setText(_translate("MainWindow", "Contas a \n"
"Pagar"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Pegasus - OP Software ®</span></p></body></html>"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
