# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tabela.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(870, 498)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(0, 30, 871, 441))
        self.tableView.setObjectName("tableView")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 470, 131, 31))
        self.textEdit.setObjectName("textEdit")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 10, 459, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnHistorico = QtWidgets.QPushButton(self.widget)
        self.btnHistorico.setObjectName("btnHistorico")
        self.horizontalLayout.addWidget(self.btnHistorico)
        self.btnAdicionarRegistro = QtWidgets.QPushButton(self.widget)
        self.btnAdicionarRegistro.setObjectName("btnAdicionarRegistro")
        self.horizontalLayout.addWidget(self.btnAdicionarRegistro)
        self.btnSalvarRegistro = QtWidgets.QPushButton(self.widget)
        self.btnSalvarRegistro.setObjectName("btnSalvarRegistro")
        self.horizontalLayout.addWidget(self.btnSalvarRegistro)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(680, 0, 160, 27))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnFechar = QtWidgets.QPushButton(self.widget1)
        self.btnFechar.setObjectName("btnFechar")
        self.horizontalLayout_3.addWidget(self.btnFechar)
        self.btnExcluirLinha = QtWidgets.QPushButton(self.widget1)
        self.btnExcluirLinha.setObjectName("btnExcluirLinha")
        self.horizontalLayout_3.addWidget(self.btnExcluirLinha)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.btnSalvarRegistro.raise_()
        self.btnHistorico.raise_()
        self.btnAdicionarRegistro.raise_()
        self.textEdit.raise_()
        self.tableView.raise_()
        self.btnFechar.raise_()
        self.btnExcluirLinha.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Pegasus 🐴 - 1.1 ®</span></p></body></html>"))
        self.btnHistorico.setText(_translate("Dialog", "Histórico de Registro"))
        self.btnAdicionarRegistro.setText(_translate("Dialog", "Adicionar Registro"))
        self.btnSalvarRegistro.setText(_translate("Dialog", "Salvar Registro"))
        self.btnFechar.setText(_translate("Dialog", "Fechar"))
        self.btnExcluirLinha.setText(_translate("Dialog", "Excluir Linha"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
